import type { ReferralRow } from "@/lib/db-adapter";

const MOCK_USER_ID = "mock-user-id";

/** Dados fictícios — substituídos por Supabase em listUserReferrals. */
export function getMockReferrals(userId: string): ReferralRow[] {
  void userId;
  const base = new Date();
  const daysAgo = (n: number) => {
    const d = new Date(base);
    d.setDate(d.getDate() - n);
    return d.toISOString();
  };

  return [
    {
      id: "mock-1",
      colaborador_id: MOCK_USER_ID,
      nome_lead: "Hugo Brito Cronemberger Freitas",
      email_lead: "hugo.cronemberger@clinicaexemplo.com.br",
      telefone_lead: "(11) 98765-4321",
      empresa: "Clínica Exemplo",
      status: "criada",
      kind: "parceiro",
      valor_venda: null,
      revenue_amount: null,
      bitrix_lead_id: null,
      bitrix_deal_id: null,
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
    },
    {
      id: "mock-2",
      colaborador_id: MOCK_USER_ID,
      nome_lead: "Dra. Marina Alves",
      email_lead: "marina.alves@hospitaldelta.com",
      telefone_lead: "(21) 99876-5432",
      empresa: "Hospital Delta",
      status: "contato",
      kind: "cliente",
      valor_venda: null,
      revenue_amount: null,
      bitrix_lead_id: "BX-1024",
      bitrix_deal_id: null,
      created_at: daysAgo(12),
      updated_at: daysAgo(5),
    },
    {
      id: "mock-3",
      colaborador_id: MOCK_USER_ID,
      nome_lead: "Dr. Ricardo Mendes",
      email_lead: null,
      telefone_lead: "(31) 99112-3344",
      empresa: "Centro Médico Horizonte",
      status: "reuniao",
      kind: "parceiro",
      valor_venda: null,
      revenue_amount: null,
      bitrix_lead_id: "BX-1088",
      bitrix_deal_id: null,
      created_at: daysAgo(28),
      updated_at: daysAgo(8),
    },
    {
      id: "mock-4",
      colaborador_id: MOCK_USER_ID,
      nome_lead: "Ana Paula Souza",
      email_lead: "ana.souza@labsaude.io",
      telefone_lead: null,
      empresa: "Lab Saúde",
      status: "proposta",
      kind: "cliente",
      valor_venda: 48000,
      revenue_amount: 48000,
      bitrix_lead_id: "BX-1102",
      bitrix_deal_id: "DL-440",
      created_at: daysAgo(45),
      updated_at: daysAgo(15),
    },
    {
      id: "mock-5",
      colaborador_id: MOCK_USER_ID,
      nome_lead: "João Pedro Nascimento",
      email_lead: "jp.nascimento@redeplus.com",
      telefone_lead: "(47) 98888-1111",
      empresa: "Rede Plus",
      status: "contratado",
      kind: "cliente",
      valor_venda: 92000,
      revenue_amount: 92000,
      bitrix_lead_id: "BX-0991",
      bitrix_deal_id: "DL-388",
      created_at: daysAgo(90),
      updated_at: daysAgo(20),
    },
    {
      id: "mock-6",
      colaborador_id: MOCK_USER_ID,
      nome_lead: "Clínica Vida Nova",
      email_lead: "contato@vidanova.med.br",
      telefone_lead: "(85) 3333-4444",
      empresa: "Clínica Vida Nova",
      status: "constituicao",
      kind: "parceiro",
      valor_venda: 65000,
      revenue_amount: 65000,
      bitrix_lead_id: "BX-1200",
      bitrix_deal_id: "DL-501",
      created_at: daysAgo(120),
      updated_at: daysAgo(30),
    },
    {
      id: "mock-7",
      colaborador_id: MOCK_USER_ID,
      nome_lead: "Felipe Torres",
      email_lead: "felipe@startuphealth.com",
      telefone_lead: null,
      empresa: null,
      status: "perdida",
      kind: "outro",
      valor_venda: null,
      revenue_amount: null,
      bitrix_lead_id: null,
      bitrix_deal_id: null,
      created_at: daysAgo(200),
      updated_at: daysAgo(180),
    },
  ];
}
